# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGn46P-L5WumpmjkQ4DMmW7QSG6jdDnv
"""

import random

board = [' ' for _ in range(9)]

def print_board():
    print(f" {board[0]} | {board[1]} | {board[2]} ")
    print("-----------")
    print(f" {board[3]} | {board[4]} | {board[5]} ")
    print("-----------")
    print(f" {board[6]} | {board[7]} | {board[8]} ")

def check_win(player):
    win_conditions = [
        [0, 1, 2], [3, 4, 5], [6, 7, 8], # Rows
        [0, 3, 6], [1, 4, 7], [2, 5, 8], # Columns
        [0, 4, 8], [2, 4, 6]            # Diagonals
    ]
    return any(all(board[spot] == player for spot in condition) for condition in win_conditions)

def get_move(player_char, prompt):
    while True:
        try:
            choice = int(input(prompt)) - 1
            if 0 <= choice <= 8 and board[choice] == ' ':
                board[choice] = player_char
                break
            else:
                print("Invalid move. Spot taken or out of range.")
        except ValueError:
            print("Please enter a number from 1 to 9.")

def computer_move():
    empty_spots = [i for i, spot in enumerate(board) if spot == ' ']
    if empty_spots:
        choice = random.choice(empty_spots)
        board[choice] = 'O'
        print(f"Computer chose position {choice + 1}")

def play_game():
    print("Welcome to Tic Tac Toe! You are X, Computer is O.")
    current_player = 'X'

    while True:
        print_board()

        if current_player == 'X':
            get_move('X', "Choose a position (1-9) for X: ")
        else:
            computer_move()

        if check_win(current_player):
            print_board()
            print(f"{current_player} wins!")
            break

        if ' ' not in board:
            print_board()
            print("It's a tie!")
            break

        current_player = 'O' if current_player == 'X' else 'X'

if __name__ == '__main__':
    play_game()